# Rename to .streamlit/secrets.toml and add your OpenAI key
OPENAI_API_KEY="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"
